name: testworkflow

on: [push]

permissions:
    id-token: write
    contents: read

jobs:
  build:
    name: build the secure properties file generator
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      #stuck here - not able to log in to Azure have tried a number of different value combinations and have confirmed az login via cloud shell with creadentials
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDS_MALLFORD }}
